/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminRegionsIndexRouteImport } from './routes/admin/_admin/regions/index'
import { Route as AdminAdminDashboardIndexRouteImport } from './routes/admin/_admin/dashboard/index'
import { Route as AdminRegionsIdInsightRouteImport } from './routes/admin/regions/$id/insight'
import { Route as AdminRegionsIdInsightReportsRouteImport } from './routes/admin/regions/$id/insight/reports'
import { Route as AdminRegionsIdInsightAiRouteImport } from './routes/admin/regions/$id/insight/ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRegionsIndexRoute = AdminAdminRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDashboardIndexRoute =
  AdminAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminRegionsIdInsightRoute = AdminRegionsIdInsightRouteImport.update({
  id: '/admin/regions/$id/insight',
  path: '/admin/regions/$id/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionsIdInsightReportsRoute =
  AdminRegionsIdInsightReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AdminRegionsIdInsightRoute,
  } as any)
const AdminRegionsIdInsightAiRoute = AdminRegionsIdInsightAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRegionsIdInsightRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/signin': typeof AuthSigninRoute
  '/admin/regions/$id/insight': typeof AdminRegionsIdInsightRouteWithChildren
  '/admin/dashboard/': typeof AdminAdminDashboardIndexRoute
  '/admin/regions/': typeof AdminAdminRegionsIndexRoute
  '/admin/regions/$id/insight/ai': typeof AdminRegionsIdInsightAiRoute
  '/admin/regions/$id/insight/reports': typeof AdminRegionsIdInsightReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/signin': typeof AuthSigninRoute
  '/admin/regions/$id/insight': typeof AdminRegionsIdInsightRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardIndexRoute
  '/admin/regions': typeof AdminAdminRegionsIndexRoute
  '/admin/regions/$id/insight/ai': typeof AdminRegionsIdInsightAiRoute
  '/admin/regions/$id/insight/reports': typeof AdminRegionsIdInsightReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/signin': typeof AuthSigninRoute
  '/admin/regions/$id/insight': typeof AdminRegionsIdInsightRouteWithChildren
  '/admin/_admin/dashboard/': typeof AdminAdminDashboardIndexRoute
  '/admin/_admin/regions/': typeof AdminAdminRegionsIndexRoute
  '/admin/regions/$id/insight/ai': typeof AdminRegionsIdInsightAiRoute
  '/admin/regions/$id/insight/reports': typeof AdminRegionsIdInsightReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/register'
    | '/auth/signin'
    | '/admin/regions/$id/insight'
    | '/admin/dashboard/'
    | '/admin/regions/'
    | '/admin/regions/$id/insight/ai'
    | '/admin/regions/$id/insight/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/register'
    | '/auth/signin'
    | '/admin/regions/$id/insight'
    | '/admin/dashboard'
    | '/admin/regions'
    | '/admin/regions/$id/insight/ai'
    | '/admin/regions/$id/insight/reports'
  id:
    | '__root__'
    | '/'
    | '/admin/_admin'
    | '/auth/register'
    | '/auth/signin'
    | '/admin/regions/$id/insight'
    | '/admin/_admin/dashboard/'
    | '/admin/_admin/regions/'
    | '/admin/regions/$id/insight/ai'
    | '/admin/regions/$id/insight/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AdminRegionsIdInsightRoute: typeof AdminRegionsIdInsightRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/regions/': {
      id: '/admin/_admin/regions/'
      path: '/regions'
      fullPath: '/admin/regions/'
      preLoaderRoute: typeof AdminAdminRegionsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dashboard/': {
      id: '/admin/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminAdminDashboardIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/regions/$id/insight': {
      id: '/admin/regions/$id/insight'
      path: '/admin/regions/$id/insight'
      fullPath: '/admin/regions/$id/insight'
      preLoaderRoute: typeof AdminRegionsIdInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions/$id/insight/reports': {
      id: '/admin/regions/$id/insight/reports'
      path: '/reports'
      fullPath: '/admin/regions/$id/insight/reports'
      preLoaderRoute: typeof AdminRegionsIdInsightReportsRouteImport
      parentRoute: typeof AdminRegionsIdInsightRoute
    }
    '/admin/regions/$id/insight/ai': {
      id: '/admin/regions/$id/insight/ai'
      path: '/ai'
      fullPath: '/admin/regions/$id/insight/ai'
      preLoaderRoute: typeof AdminRegionsIdInsightAiRouteImport
      parentRoute: typeof AdminRegionsIdInsightRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminDashboardIndexRoute: typeof AdminAdminDashboardIndexRoute
  AdminAdminRegionsIndexRoute: typeof AdminAdminRegionsIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminDashboardIndexRoute: AdminAdminDashboardIndexRoute,
  AdminAdminRegionsIndexRoute: AdminAdminRegionsIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRegionsIdInsightRouteChildren {
  AdminRegionsIdInsightAiRoute: typeof AdminRegionsIdInsightAiRoute
  AdminRegionsIdInsightReportsRoute: typeof AdminRegionsIdInsightReportsRoute
}

const AdminRegionsIdInsightRouteChildren: AdminRegionsIdInsightRouteChildren = {
  AdminRegionsIdInsightAiRoute: AdminRegionsIdInsightAiRoute,
  AdminRegionsIdInsightReportsRoute: AdminRegionsIdInsightReportsRoute,
}

const AdminRegionsIdInsightRouteWithChildren =
  AdminRegionsIdInsightRoute._addFileChildren(
    AdminRegionsIdInsightRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSigninRoute: AuthSigninRoute,
  AdminRegionsIdInsightRoute: AdminRegionsIdInsightRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
